package com.example.model

import androidx.compose.ui.graphics.Color
import com.example.ui.theme.NeonCyan
import com.example.ui.theme.NeonPink
import com.example.ui.theme.NeonGreen
import com.example.ui.theme.NeonYellow
import com.example.ui.theme.NeonPurple

/**
 * Normalized 2D point (0.0f .. 1.0f) relative to the target canvas bounds.
 */
data class DrawingPoint(
    val x: Float,
    val y: Float
)

/**
 * Single continuous brush stroke or line path consisting of sequential points.
 */
data class DrawingStroke(
    val id: String,
    val points: List<DrawingPoint>,
    val colorHex: String = "#00F0FF",
    val strokeWidth: Float = 4f,
    val strokeType: StrokeType = StrokeType.LINE,
    val isClosed: Boolean = false
) {
    fun parseColor(): Color {
        return try {
            val cleanHex = colorHex.removePrefix("#")
            when (cleanHex.length) {
                6 -> Color(android.graphics.Color.parseColor("#$cleanHex"))
                8 -> Color(android.graphics.Color.parseColor("#$cleanHex"))
                3 -> {
                    val r = cleanHex[0]
                    val g = cleanHex[1]
                    val b = cleanHex[2]
                    Color(android.graphics.Color.parseColor("#$r$r$g$g$b$b"))
                }
                else -> NeonCyan
            }
        } catch (e: Exception) {
            NeonCyan
        }
    }
}

enum class StrokeType {
    LINE,
    CURVE,
    DOT,
    OUTLINE,
    FILL_HATCH
}

/**
 * High-performance vector layer for organizing complex multi-part drawings.
 * Layers allow the AI and user to separate lineart, anatomy, shading, and accents.
 */
data class DrawingLayer(
    val id: String = java.util.UUID.randomUUID().toString(),
    val name: String = "Layer 1",
    val isVisible: Boolean = true,
    val isLocked: Boolean = false,
    val opacity: Float = 1.0f,
    val strokes: List<DrawingStroke> = emptyList(),
    val colorTagHex: String = "#00F0FF"
) {
    val totalPoints: Int get() = strokes.sumOf { it.points.size }
}

/**
 * Complete set of drawing instructions generated by Puter.js AI or synthesizers,
 * organized into performant state-based vector layers.
 */
data class ArtHaxInstructionSet(
    val id: String,
    val title: String,
    val prompt: String,
    val model: String,
    val strokes: List<DrawingStroke> = emptyList(),
    val layers: List<DrawingLayer> = if (strokes.isNotEmpty()) {
        listOf(
            DrawingLayer(
                id = "default_layer",
                name = "Main Vector Layer",
                strokes = strokes
            )
        )
    } else {
        emptyList()
    },
    val canvasAspectRatio: Float = 1.0f,
    val totalEstimatedPoints: Int = if (layers.isNotEmpty()) layers.sumOf { it.totalPoints } else strokes.sumOf { it.points.size },
    val generatedAtMillis: Long = System.currentTimeMillis()
) {
    /**
     * Aggregated list of visible active strokes across all enabled layers.
     */
    val activeStrokes: List<DrawingStroke>
        get() {
            return if (layers.isNotEmpty()) {
                layers.filter { it.isVisible }.flatMap { layer ->
                    if (layer.opacity < 0.99f) {
                        // Apply layer opacity into stroke colors
                        layer.strokes.map { stroke ->
                            val baseColor = stroke.parseColor()
                            val adjustedColor = baseColor.copy(alpha = baseColor.alpha * layer.opacity)
                            stroke.copy(colorHex = String.format("#%08X", (adjustedColor.value.toLong() and 0xFFFFFFFFL)))
                        }
                    } else {
                        layer.strokes
                    }
                }
            } else {
                strokes
            }
        }
}

/**
 * Snapshot state for undo / redo history stack in the layer management system.
 */
data class LayerHistoryState(
    val layers: List<DrawingLayer>,
    val actionDescription: String = "Edit"
)

/**
 * Puter.js AI Model configuration
 */
data class AiModelOption(
    val id: String,
    val name: String,
    val provider: String,
    val badge: String,
    val description: String,
    val isRecommended: Boolean = false,
    val isFree: Boolean = true
)

/**
 * Authentication and Account state for Puter.js
 */
data class PuterAuthState(
    val isSignedIn: Boolean = false,
    val username: String? = null,
    val email: String? = null,
    val userId: String? = null,
    val token: String? = null,
    val isFreeTier: Boolean = true,
    val statusMessage: String = "Guest mode (Free Models Active)"
)

/**
 * Sekai and gaming presets ready for instant execution
 */
data class SekaiPreset(
    val id: String,
    val title: String,
    val category: String,
    val prompt: String,
    val previewIcon: String,
    val strokeCountApprox: Int,
    val defaultColorHex: String
)

/**
 * Bounding box on screen (normalized 0.0f .. 1.0f) where target drawing canvas is located
 */
data class CalibrationBounds(
    val left: Float = 0.06f,
    val top: Float = 0.22f,
    val right: Float = 0.94f,
    val bottom: Float = 0.78f
) {
    val width: Float get() = (right - left).coerceAtLeast(0.1f)
    val height: Float get() = (bottom - top).coerceAtLeast(0.1f)
}

/**
 * Live execution state of the drawing engine
 */
sealed class ExecutionState {
    object Idle : ExecutionState()
    data class Generating(val progress: Float, val message: String) : ExecutionState()
    data class Ready(val instructionSet: ArtHaxInstructionSet) : ExecutionState()
    data class Drawing(
        val currentStrokeIndex: Int,
        val totalStrokes: Int,
        val currentPointIndex: Int,
        val totalPoints: Int,
        val progress: Float,
        val activePoint: DrawingPoint?,
        val activeColorHex: String
    ) : ExecutionState()
    object Paused : ExecutionState()
    data class Completed(val totalStrokesDrawn: Int, val durationMs: Long) : ExecutionState()
    data class Error(val message: String) : ExecutionState()
}

/**
 * User customization and tuning parameters for stroke execution
 */
data class DrawingSettings(
    val speedMultiplier: Float = 2.0f, // 0.5x to 5.0x
    val strokeDelayMs: Long = 30L,     // delay between gestures
    val pointStepInterpolation: Int = 3, // point density
    val previewGlowIntensity: Float = 0.8f,
    val showPreviewOverlay: Boolean = true,
    val autoMinimizeOnExecute: Boolean = true,
    val vibrationFeedback: Boolean = true,
    val unrestrictedMode: Boolean = false, // Unrestricted Mode (prompts won't be blocked, great for 2D horror games)
    val copyrightBypassMode: Boolean = false, // Bypass copyright restrictions by veering prompt to clean non-copyright wording
    val edgeHugging: Boolean = true // Snap floating bubble to closest screen edge when released
)

/**
 * Chat message item for floating AI chat assistant window
 */
data class ChatMessage(
    val id: String = java.util.UUID.randomUUID().toString(),
    val sender: ChatSender,
    val text: String,
    val timestampMillis: Long = System.currentTimeMillis(),
    val modelName: String? = null,
    val isInstructionGenerated: Boolean = false,
    val instructionSet: ArtHaxInstructionSet? = null
)

enum class ChatSender {
    USER,
    ASSISTANT,
    SYSTEM
}
